name: インシデント
description: ミスの再発防止ログ
title: "[Incident] YYYY-MM-DD Title"
labels: ["インシデント"]
body:
  - type: input
    id: date
    attributes:
      label: 日付（YYYY-MM-DD）
      placeholder: "2026-02-06"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 2-3文で何が起きたか
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 影響
      description: 何が問題になったか
    validations:
      required: true
  - type: textarea
    id: root_cause
    attributes:
      label: 原因
      description: なぜ起きたか
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: 再発防止
      description: どう防ぐか
    validations:
      required: true
  - type: textarea
    id: followups
    attributes:
      label: 追加対応
      description: 追対応があれば
    validations:
      required: false
