name: セッション提案
description: 火曜/木曜のナレッジ共有セッションを提案
title: "[Session] YYYY-MM-DD Title"
labels: ["セッション"]
body:
  - type: input
    id: date
    attributes:
      label: 日付（YYYY-MM-DD）
      placeholder: "2026-02-10"
    validations:
      required: true
  - type: dropdown
    id: slot
    attributes:
      label: 枠
      options:
        - 1_Tue
        - 2_Thu
        - 3_Others
    validations:
      required: true
  - type: dropdown
    id: theme
    attributes:
      label: テーマ
      options:
        - 基礎
        - ティップス
        - トレンド
        - ツール
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: 目的
      description: 参加者が理解/意思決定できる状態
    validations:
      required: true
  - type: textarea
    id: key_points
    attributes:
      label: 要点
      description: 3-5個
      placeholder: "- ..."
    validations:
      required: true
  - type: textarea
    id: assets
    attributes:
      label: 必要素材
      description: スライド、デモ、スクショ、データなど
    validations:
      required: false
