name: Tip Idea
description: Capture a practical AI tip
title: "[Tip] Short Title"
labels: ["tip"]
body:
  - type: textarea
    id: tip
    attributes:
      label: Tip
      description: Describe the tip in 2-3 sentences
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Where it applies
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: URL (optional)
    validations:
      required: false
