name: ティップスメモ
description: 実務で使えるAIの小ネタ
title: "[Tip] Title"
labels: ["ティップス"]
body:
  - type: textarea
    id: tip
    attributes:
      label: ティップス
      description: 2-3文で説明
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: ユースケース
      description: どこで使うか
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: URL（任意）
    validations:
      required: false
