name: トレンドメモ
description: 木曜で取り上げる候補のトレンド/ニュース
title: "[Trend] YYYY-MM-DD Title"
labels: ["トレンド"]
body:
  - type: input
    id: source
    attributes:
      label: 出典
      placeholder: "媒体 / 企業"
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: 日付（YYYY-MM-DD）
      placeholder: "2026-02-05"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 2-4文
    validations:
      required: true
  - type: textarea
    id: why_it_matters
    attributes:
      label: 重要性
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: URL
    validations:
      required: false
